---
driver:
  name: vagrant

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbosity: 3
  ansible_verbose: true
  extra_vars:
    ansible_python_interpreter: '/usr/local/bin/python'

platforms:
  - name: freebsd-10.3-amd64
    driver:
      box: trombik/ansible-freebsd-10.3-amd64
      box_check_update: true
    driver_config:
      ssh:
        shell: '/bin/sh'

suites:
  - name: default
    provisioner:
      name: ansible_playbook
      playbook: test/integration/default.yml
    verifier:
      name: shell
      command: rspec -c -f d -I spec/serverspec spec/serverspec/default_spec.rb
