require "socket"
# @return [String] public IP address of workstation used for egress traffic
def local_ip
  @local_ip ||= begin
    # turn off reverse DNS resolution temporarily
    orig = Socket.do_not_reverse_lookup
    Socket.do_not_reverse_lookup = true

    # open UDP socket so that it never send anything over the network
    UDPSocket.open do |s|
      s.connect "8.8.8.8", 1 # any global IP address works here
      s.addr.last
    end
  ensure
    Socket.do_not_reverse_lookup = orig
  end
end

# @return [Integer] default listening port
def local_port
  8080
end

# @return [String] the proxy URL
def http_proxy_url
  "http://#{local_ip}:#{local_port}"
end

# @return [TrueClass,FalseClass] whether or not the port is listening
def proxy_running?
  socket = TCPSocket.new(local_ip, local_port)
  true
rescue SocketError, Errno::ECONNREFUSED,
       Errno::EHOSTUNREACH, Errno::ENETUNREACH, IOError
  false
rescue Errno::EPERM, Errno::ETIMEDOUT
  false
ensure
  socket && socket.close
end
http_proxy = proxy_running? ? http_proxy_url : ""

# Vagrantfile
Vagrant.configure("2") do |config|
  config.ssh.shell = "/bin/sh"
  config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end

  boxen = [
    "trombik/ansible-freebsd-10.3-amd64",
    "trombik/ansible-ubuntu-14.04-amd64",
    "trombik/ansible-centos-7.2-x86_64"
  ]
  boxen.each_with_index do |box_name, i|
    config.vm.define "server#{i}" do |c|
      c.vm.box = box_name
      ip = "192.168.21." + (200 + i).to_s
      c.vm.network "private_network", ip: ip
      c.vm.hostname = "server#{i}.virtualbox.reallyenglish.com"
      c.vm.provision :ansible do |ansible|
        ansible.limit = ip
        ansible.playbook = "site.yml"
        ansible.extra_vars = {
          http_proxy: http_proxy,
          https_proxy: http_proxy,
          no_proxy: "localhost,127.0.0.1,.example.com"
        }
        ansible.extra_vars["ansible_python_interpreter"] = "/usr/local/bin/python" if box_name =~ /bsd/
        ansible.inventory_path = "inventories/staging"
        ansible.verbose = "v"
      end
    end
  end
end
# vim: ft=ruby
